# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_treasure_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='img_url',
            field=models.CharField(max_length=100),
        ),
    ]
